// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: Copyright (c) 2024 Flight Hub Team

//! Property-based invariant tests for the flight-axis pipeline (external integration tests).
//!
//! These tests exercise the public API from outside the crate, verifying mathematical
//! invariants hold across arbitrary inputs generated by proptest:
//!
//! - Deadzone zeroes inputs inside the zone (symmetrically)
//! - Expo curve output stays in [-1.0, 1.0]
//! - Expo curve preserves sign
//! - A deadzone + curve pipeline always produces finite output
//! - `f32::clamp` output never exceeds its bounds

use flight_axis::{
    AxisFrame, PipelineBuilder,
    nodes::{CurveNode, DeadzoneNode, Node},
};
use proptest::prelude::*;

proptest! {
    /// Invariant 1: Symmetric deadzone removes small inputs symmetrically.
    ///
    /// - For |input| < deadzone_radius  → output must be 0.0.
    /// - For |input| >= deadzone_radius → |output| must be > 0.0.
    #[test]
    fn deadzone_output_zero_within_zone(
        input   in -0.1f32..0.1f32,
        deadzone in 0.05f32..0.15f32,
    ) {
        let mut node = DeadzoneNode::new(deadzone);
        let mut frame = AxisFrame::new(input, 1_000_000);
        node.step(&mut frame);

        if input.abs() < deadzone {
            prop_assert_eq!(
                frame.out, 0.0,
                "input={} is within deadzone={}, expected 0.0, got {}",
                input, deadzone, frame.out
            );
        } else {
            prop_assert!(
                frame.out.abs() > 0.0,
                "input={} is outside deadzone={}, expected nonzero, got {}",
                input, deadzone, frame.out
            );
        }
    }

    /// Invariant 2: Expo curve output is always in [-1.0, 1.0] for inputs in [-1.0, 1.0].
    #[test]
    fn expo_output_bounded(
        input in -1.0f32..=1.0f32,
        expo  in  0.0f32..=1.0f32,
    ) {
        let mut node = CurveNode::new(expo);
        let mut frame = AxisFrame::new(input, 1_000_000);
        node.step(&mut frame);

        prop_assert!(
            (-1.0..=1.0).contains(&frame.out),
            "expo curve output {} out of [-1, 1] for input={}, expo={}",
            frame.out, input, expo
        );
    }

    /// Invariant 3: Expo curve preserves sign for strictly positive inputs.
    #[test]
    fn expo_preserves_sign(
        input in 0.01f32..=1.0f32,
        expo  in 0.0f32..=1.0f32,
    ) {
        let mut node = CurveNode::new(expo);
        let mut frame = AxisFrame::new(input, 1_000_000);
        node.step(&mut frame);

        prop_assert!(
            frame.out >= 0.0,
            "expo curve should preserve positive sign: input={}, expo={}, output={}",
            input, expo, frame.out
        );
    }

    /// Invariant 4: A pipeline with deadzone + curve always produces finite output
    /// for any valid input in [-1.0, 1.0].
    #[test]
    fn pipeline_output_finite(input in -1.0f32..=1.0f32) {
        let pipeline = PipelineBuilder::new()
            .deadzone(0.05)
            .curve(0.3)
            .expect("valid expo")
            .compile()
            .expect("pipeline compiles");

        let mut state = pipeline.create_state();
        let mut frame = AxisFrame::new(input, 1_000_000);
        pipeline.process(&mut frame, &mut state);

        prop_assert!(
            frame.out.is_finite(),
            "pipeline output should be finite for input={}, got {}",
            input, frame.out
        );
    }

    /// Invariant 5: Saturation clamp — `f32::clamp` output never exceeds the bounds.
    ///
    /// For any finite f32 value, clamping to [-1.0, 1.0] must produce a finite
    /// value within that range.
    #[test]
    fn clamp_never_exceeds_bounds(input in f32::MIN..=f32::MAX) {
        let clamped = input.clamp(-1.0_f32, 1.0_f32);

        prop_assert!(
            (-1.0..=1.0).contains(&clamped),
            "clamp({}) = {} exceeded bounds [-1.0, 1.0]",
            input, clamped
        );
        prop_assert!(
            clamped.is_finite(),
            "clamp({}) = {} is not finite",
            input, clamped
        );
    }
}
