Feature: Service Config Schema Documentation
  As a flight simulation enthusiast
  I want the service config schema to be documented and validated
  So that I can write correct configuration files with editor assistance

  Background:
    Given the OpenFlight service installer is available

  Scenario: Config schema is documented as JSON Schema
    When the schemas directory is inspected
    Then a JSON Schema file describing the service configuration is present

  Scenario: JSON Schema is bundled with installer
    When the installer package is inspected
    Then the JSON Schema file for service config is included in the package

  Scenario: Config file is validated against schema on load
    Given a service config file contains an unknown top-level key
    When the service attempts to load the config file
    Then the load fails with a validation error referencing the unknown key

  Scenario: Schema version is embedded in config files
    Given a valid service config file is generated by the service
    When the config file is inspected
    Then it contains a "$schema" field pointing to the versioned JSON Schema URL
