@REQ-289 @product
Feature: CLI tab completion for bash, zsh, and fish with dynamic device and profile name suggestions  @AC-289.1
  Scenario: flightctl completion bash outputs valid bash completion script
    Given the flightctl binary is installed
    When the user runs flightctl completion bash
    Then the output SHALL be a valid bash completion script that can be sourced without errors  @AC-289.2
  Scenario: flightctl completion zsh outputs valid zsh completion
    Given the flightctl binary is installed
    When the user runs flightctl completion zsh
    Then the output SHALL be a valid zsh completion script that can be loaded without errors  @AC-289.3
  Scenario: flightctl completion fish outputs valid fish completion
    Given the flightctl binary is installed
    When the user runs flightctl completion fish
    Then the output SHALL be a valid fish completion script that can be sourced without errors  @AC-289.4
  Scenario: Completion covers all subcommands and flags
    Given a bash completion script generated by flightctl completion bash
    When tab completion is triggered for the flightctl command
    Then all documented subcommands and their flags SHALL appear as completion candidates  @AC-289.5
  Scenario: Device names and profile names are offered as dynamic completions
    Given the service is running with two devices and three profiles loaded
    When the user tab-completes a subcommand argument that accepts a device or profile name
    Then the current device names and profile names SHALL be offered as completion candidates  @AC-289.6
  Scenario: Generated completions pass shell syntax validation
    Given completion scripts have been generated for bash, zsh, and fish
    When each script is checked with its respective shell syntax validator
    Then all three scripts SHALL pass validation with no syntax errors reported
