@REQ-505 @product
Feature: Config File Schema Documentation — Reference Docs Generated from Schema  @AC-505.1
  Scenario: cargo xtask gen-docs generates reference documentation
    Given the project source contains annotated configuration schema definitions
    When `cargo xtask gen-docs` is executed
    Then the command SHALL complete successfully and report documentation generated  @AC-505.2
  Scenario: Documentation includes field names types defaults and descriptions
    Given reference documentation has been generated by cargo xtask gen-docs
    When the output Markdown is inspected
    Then each config field SHALL have its name, type, default value, and description documented  @AC-505.3
  Scenario: Documentation is published as Markdown in docs/reference/
    Given cargo xtask gen-docs has been run
    When the docs/reference/ directory is listed
    Then at least one Markdown file covering configuration options SHALL be present  @AC-505.4
  Scenario: Documentation is regenerated as part of CI validate step
    Given the CI validate pipeline is defined
    When the validate step runs
    Then gen-docs SHALL be invoked and any drift between schema and docs SHALL cause CI to fail
