// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: Copyright (c) 2024 Flight Hub Team

//! Generate COMPATIBILITY.md from `compat/` YAML manifests.
//!
//! Run with: `cargo xtask gen-compat`

use anyhow::{Context, Result};
use std::{
    fmt::Write as FmtWrite,
    fs,
    path::{Path, PathBuf},
};

/// Entry point for `cargo xtask gen-compat`.
pub fn run_gen_compat() -> Result<()> {
    let compat_dir = Path::new("compat");
    if !compat_dir.exists() {
        anyhow::bail!("compat/ directory not found. Run from workspace root.");
    }

    let devices = collect_manifests(&compat_dir.join("devices"))?;
    let games = collect_manifests(&compat_dir.join("games"))?;

    let mut out = String::new();
    writeln!(out, "# OpenFlight Compatibility Matrix")?;
    writeln!(out)?;
    writeln!(
        out,
        "> Auto-generated by `cargo xtask gen-compat`. Do not edit manually."
    )?;
    writeln!(out)?;

    // Devices section
    writeln!(out, "## Hardware Devices")?;
    writeln!(out)?;
    writeln!(
        out,
        "| Device | Vendor ID | Product ID | Axes | Buttons | FFB | Tier |"
    )?;
    writeln!(
        out,
        "|--------|-----------|------------|------|---------|-----|------|"
    )?;

    for path in &devices {
        if let Ok(entry) = render_device_row(path) {
            writeln!(out, "{}", entry)?;
        }
    }
    writeln!(out)?;

    // Games section
    writeln!(out, "## Game Integrations")?;
    writeln!(out)?;
    writeln!(
        out,
        "| Game | Integration | Telemetry | Control Injection | FFB | HIL Tested |"
    )?;
    writeln!(
        out,
        "|------|-------------|-----------|-------------------|-----|------------|"
    )?;

    for path in &games {
        if let Ok(entry) = render_game_row(path) {
            writeln!(out, "{}", entry)?;
        }
    }
    writeln!(out)?;

    // Support tier legend
    writeln!(out, "## Support Tier Legend")?;
    writeln!(out)?;
    writeln!(out, "| Tier | Meaning |")?;
    writeln!(out, "|------|---------|")?;
    writeln!(out, "| 1 | Automated trace tests + recent HIL validation |")?;
    writeln!(
        out,
        "| 2 | Automated tests (no HIL) + community confirmation |"
    )?;
    writeln!(out, "| 3 | Compiles / best-effort — no guarantees |")?;

    let output_path = "COMPATIBILITY.md";
    fs::write(output_path, &out).with_context(|| format!("Failed to write {output_path}"))?;

    println!("✓ Written {output_path} ({} bytes)", out.len());
    println!("  Devices: {}", devices.len());
    println!("  Games:   {}", games.len());
    Ok(())
}

/// Collect `.yaml` manifest paths from a directory tree, sorted.
fn collect_manifests(dir: &Path) -> Result<Vec<PathBuf>> {
    if !dir.exists() {
        return Ok(Vec::new());
    }
    let mut paths = Vec::new();
    collect_yaml(dir, &mut paths);
    paths.sort();
    Ok(paths)
}

fn collect_yaml(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let p = entry.path();
        if p.is_dir() {
            collect_yaml(&p, out);
        } else if p.extension().is_some_and(|e| e == "yaml") {
            out.push(p);
        }
    }
}

fn render_device_row(path: &Path) -> Result<String> {
    let text = fs::read_to_string(path)?;
    let doc: serde_yaml::Value = serde_yaml::from_str(&text)?;

    let name = doc["device"]["name"].as_str().unwrap_or("?").to_string();
    let vid = doc["device"]["usb"]["vendor_id"]
        .as_u64()
        .map_or_else(|| "?".to_string(), |v| format!("0x{v:04X}"));
    let pid = doc["device"]["usb"]["product_id"]
        .as_u64()
        .map_or_else(|| "?".to_string(), |v| format!("0x{v:04X}"));
    let axes = doc["capabilities"]["axes"]["count"]
        .as_u64()
        .map_or_else(|| "?".to_string(), |v| v.to_string());
    let buttons = doc["capabilities"]["buttons"]
        .as_u64()
        .map_or_else(|| "?".to_string(), |v| v.to_string());
    let ffb = if doc["capabilities"]["force_feedback"]
        .as_bool()
        .unwrap_or(false)
    {
        "✓"
    } else {
        "✗"
    };
    let tier = doc["support"]["tier"]
        .as_u64()
        .map_or_else(|| "?".to_string(), |v| v.to_string());

    Ok(format!(
        "| {name} | {vid} | {pid} | {axes} | {buttons} | {ffb} | {tier} |"
    ))
}

fn render_game_row(path: &Path) -> Result<String> {
    let text = fs::read_to_string(path)?;
    let doc: serde_yaml::Value = serde_yaml::from_str(&text)?;

    let name = doc["game"]["name"].as_str().unwrap_or("?").to_string();
    let mechanism = doc["integration"]["mechanism"]
        .as_str()
        .unwrap_or("?")
        .to_string();
    let telemetry = bool_to_check(doc["features"]["telemetry_read"].as_bool());
    let control = {
        let std_events = doc["features"]["control_injection"]["standard_events"]
            .as_bool()
            .unwrap_or(false);
        let direct = doc["features"]["control_injection"]["direct"]
            .as_bool()
            .unwrap_or(false);
        let dataref = doc["features"]["control_injection"]["dataref_write"]
            .as_bool()
            .unwrap_or(false);
        if std_events || direct || dataref {
            "✓"
        } else {
            "✗"
        }
    };
    let ffb = bool_to_check(doc["features"]["force_feedback_translation"].as_bool());
    let hil = bool_to_check(doc["test_coverage"]["hil"].as_bool());

    Ok(format!(
        "| {name} | {mechanism} | {telemetry} | {control} | {ffb} | {hil} |"
    ))
}

fn bool_to_check(v: Option<bool>) -> &'static str {
    match v {
        Some(true) => "✓",
        _ => "✗",
    }
}
