// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: Copyright (c) 2024 Flight Hub Team

//! Property-based invariant tests for HID axis calibration and normalisation.
//!
//! Tests verify that [`flight_hid::calibration::AxisCalibration`] upholds the
//! following mathematical invariants across arbitrary hardware-representative
//! inputs generated by proptest:
//!
//! 1. **Output always finite** — `normalize` never produces NaN or Inf.
//! 2. **Output always bounded** — result ∈ `[output_min, output_max]`.
//! 3. **Monotonic mapping** — if `raw_a ≤ raw_b` then
//!    `normalize(raw_a) ≤ normalize(raw_b)` (or `≥` when `reversed = true`).
//! 4. **Symmetric centre maps to zero** — for a symmetric stick calibration
//!    (raw_center = exact midpoint of raw range, output = [-1, 1]),
//!    `normalize(raw_center)` is approximately 0.0.
//! 5. **Endpoint mapping** — without deadzone, `raw_min → output_min` and
//!    `raw_max → output_max`.
//! 6. **Deadzone kills small inputs** — raw values within the deadzone radius
//!    of `raw_center` map to the same value as `normalize(raw_center)`.
//! 7. **Reverse flag inverts** — `normalize(raw_min) == output_max` and
//!    `normalize(raw_max) == output_min` when `reversed = true` and no deadzone.
//! 8. **Resolution tolerance** — 10-bit (0–1023), 12-bit (0–4095), and 16-bit
//!    (0–65535) axes all produce finite, bounded output.

use flight_hid::calibration::AxisCalibration;
use proptest::prelude::*;

// ---------------------------------------------------------------------------
// Shared strategies — values derived from fractions to avoid prop_assume rejects
// ---------------------------------------------------------------------------

/// Generate a valid deadzone fraction in `[0.0, 0.49]`.
fn deadzone() -> impl Strategy<Value = f32> {
    0.0f32..0.5f32
}

/// Generate a symmetric bipolar output range `(-bound, bound)` with `bound ∈ (0.01, 2]`.
fn bipolar_output() -> impl Strategy<Value = (f32, f32)> {
    (0.01f32..=2.0f32).prop_map(|b| (-b, b))
}

/// Generate a complete `AxisCalibration` with all values derived from fractions so
/// that `raw_min < raw_max` and `raw_min ≤ raw_center ≤ raw_max` are guaranteed.
fn any_calibration() -> impl Strategy<Value = AxisCalibration> {
    (
        0u32..65534u32,  // raw_min
        1u32..=65535u32, // raw_spread (ensures raw_max > raw_min)
        0.0f32..=1.0f32, // raw_center as fraction of [raw_min, raw_max]
        deadzone(),
        bipolar_output(),
        proptest::bool::ANY,
    )
        .prop_map(
            |(raw_min, raw_spread, ctr_frac, dz, (out_min, out_max), reversed)| {
                let raw_max = raw_min.saturating_add(raw_spread);
                let raw_range = (raw_max - raw_min) as f32;
                let raw_center = raw_min + (ctr_frac * raw_range) as u32;
                AxisCalibration {
                    raw_min,
                    raw_max,
                    raw_center: raw_center.min(raw_max),
                    deadzone: dz,
                    output_min: out_min,
                    output_max: out_max,
                    reversed,
                }
            },
        )
}

/// Generate a `(AxisCalibration, raw_input)` pair where `raw_input ∈ [raw_min, raw_max]`.
fn calibration_with_raw() -> impl Strategy<Value = (AxisCalibration, u32)> {
    (
        0u32..65534u32,
        1u32..=65535u32,
        0.0f32..=1.0f32, // raw_center fraction
        0.0f32..=1.0f32, // raw input fraction
        deadzone(),
        bipolar_output(),
        proptest::bool::ANY,
    )
        .prop_map(
            |(raw_min, raw_spread, ctr_frac, raw_frac, dz, (out_min, out_max), reversed)| {
                let raw_max = raw_min.saturating_add(raw_spread);
                let raw_range = (raw_max - raw_min) as f32;
                let raw_center = raw_min + (ctr_frac * raw_range) as u32;
                let raw = raw_min + (raw_frac * raw_range) as u32;
                (
                    AxisCalibration {
                        raw_min,
                        raw_max,
                        raw_center: raw_center.min(raw_max),
                        deadzone: dz,
                        output_min: out_min,
                        output_max: out_max,
                        reversed,
                    },
                    raw.min(raw_max),
                )
            },
        )
}

/// Generate a `(AxisCalibration, raw_a, raw_b)` triple where `raw_a ≤ raw_b`.
fn calibration_with_ordered_pair() -> impl Strategy<Value = (AxisCalibration, u32, u32)> {
    (
        0u32..65534u32,
        1u32..=65535u32,
        0.0f32..=1.0f32, // raw_center fraction
        0.0f32..=1.0f32, // raw_a fraction
        0.0f32..=1.0f32, // raw_b fraction
        deadzone(),
        proptest::bool::ANY,
    )
        .prop_map(
            |(raw_min, raw_spread, ctr_frac, a_frac, b_frac, dz, reversed)| {
                let raw_max = raw_min.saturating_add(raw_spread);
                let raw_range = (raw_max - raw_min) as f32;
                let raw_center = raw_min + (ctr_frac * raw_range) as u32;
                // Sort fractions so raw_a ≤ raw_b.
                let (af, bf) = if a_frac <= b_frac {
                    (a_frac, b_frac)
                } else {
                    (b_frac, a_frac)
                };
                let raw_a = raw_min + (af * raw_range) as u32;
                let raw_b = raw_min + (bf * raw_range) as u32;
                (
                    AxisCalibration {
                        raw_min,
                        raw_max,
                        raw_center: raw_center.min(raw_max),
                        deadzone: dz,
                        output_min: -1.0,
                        output_max: 1.0,
                        reversed,
                    },
                    raw_a.min(raw_max),
                    raw_b.min(raw_max),
                )
            },
        )
}

// ---------------------------------------------------------------------------
// Invariant 1 & 2: Output is always finite and bounded
// ---------------------------------------------------------------------------

proptest! {
    /// For any raw value in `[raw_min, raw_max]`, the output is finite and
    /// lies within `[output_min, output_max]`.
    #[test]
    fn output_always_finite_and_bounded((cal, raw) in calibration_with_raw()) {
        let out = cal.normalize(raw);

        prop_assert!(
            out.is_finite(),
            "normalize({raw}) is not finite (got {out}); \
             raw_range=[{},{}] output=[{},{}] dz={}",
            cal.raw_min, cal.raw_max, cal.output_min, cal.output_max, cal.deadzone
        );
        prop_assert!(
            (cal.output_min..=cal.output_max).contains(&out),
            "normalize({raw}) = {out} is outside [{}, {}]; \
             raw_range=[{},{}] dz={} reversed={}",
            cal.output_min, cal.output_max,
            cal.raw_min, cal.raw_max, cal.deadzone, cal.reversed
        );
    }
}

// ---------------------------------------------------------------------------
// Invariant 3: Monotonic mapping
// ---------------------------------------------------------------------------

proptest! {
    /// For `raw_a ≤ raw_b`, the mapping is non-decreasing (forward) or
    /// non-increasing (reversed).
    #[test]
    fn mapping_is_monotonic((cal, raw_a, raw_b) in calibration_with_ordered_pair()) {
        // raw_a ≤ raw_b is guaranteed by the strategy.
        let out_a = cal.normalize(raw_a);
        let out_b = cal.normalize(raw_b);

        if cal.reversed {
            prop_assert!(
                out_a >= out_b,
                "reversed axis should be non-increasing: \
                 raw_a={raw_a} → {out_a}, raw_b={raw_b} → {out_b}"
            );
        } else {
            prop_assert!(
                out_a <= out_b,
                "forward axis should be non-decreasing: \
                 raw_a={raw_a} → {out_a}, raw_b={raw_b} → {out_b}"
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Invariant 4: Symmetric centre maps to (approximately) zero
// ---------------------------------------------------------------------------

proptest! {
    /// For a symmetric stick calibration (raw_center = exact integer midpoint,
    /// output = [-1, 1]), `normalize(raw_center)` is within floating-point
    /// rounding of 0.0.
    ///
    /// Uses even raw_max so the midpoint is an exact integer; this isolates
    /// floating-point arithmetic precision from range-related skew.
    #[test]
    fn symmetric_center_maps_near_zero(
        half in 1u32..32767u32,
        dz in deadzone(),
        reversed in proptest::bool::ANY,
    ) {
        let raw_max = half * 2;
        let raw_center = half; // exact integer midpoint

        let cal = AxisCalibration {
            raw_min: 0,
            raw_max,
            raw_center,
            deadzone: dz,
            output_min: -1.0,
            output_max: 1.0,
            reversed,
        };

        let out = cal.normalize(raw_center);
        // For a perfectly centred axis the output is 0.0 regardless of
        // reversal (both halves are equal length, so centre = 0).
        prop_assert!(
            out.abs() < 1e-5,
            "symmetric centre raw={raw_center} (range 0..{raw_max}) → {out}, expected ~0; \
             dz={dz} reversed={reversed}"
        );
    }
}

// ---------------------------------------------------------------------------
// Invariant 5: Endpoint mapping (no deadzone)
// ---------------------------------------------------------------------------

proptest! {
    /// Without deadzone, `raw_min → output_min` and `raw_max → output_max`
    /// (forward) or the inverse (reversed).
    #[test]
    fn endpoints_map_correctly_without_deadzone(cal in any_calibration()) {
        let cal = AxisCalibration { deadzone: 0.0, ..cal };

        let at_min = cal.normalize(cal.raw_min);
        let at_max = cal.normalize(cal.raw_max);

        let (expected_at_min, expected_at_max) = if cal.reversed {
            (cal.output_max, cal.output_min)
        } else {
            (cal.output_min, cal.output_max)
        };

        prop_assert!(
            (at_min - expected_at_min).abs() < 1e-4,
            "raw_min={} → {at_min}, expected {expected_at_min}; \
             reversed={} out=[{},{}]",
            cal.raw_min, cal.reversed, cal.output_min, cal.output_max
        );
        prop_assert!(
            (at_max - expected_at_max).abs() < 1e-4,
            "raw_max={} → {at_max}, expected {expected_at_max}; \
             reversed={} out=[{},{}]",
            cal.raw_max, cal.reversed, cal.output_min, cal.output_max
        );
    }
}

// ---------------------------------------------------------------------------
// Invariant 6: Deadzone — inputs near raw_center snap to the centre value
// ---------------------------------------------------------------------------

proptest! {
    /// Raw values strictly inside the deadzone radius of `raw_center` must map
    /// to the same output value as `normalize(raw_center)`.
    ///
    /// Uses a symmetric calibration (raw_center at exact integer midpoint) so
    /// that the deadzone radius in raw counts is easy to compute.
    #[test]
    fn deadzone_snaps_inputs_near_center(
        half in 100u32..32000u32,
        dz in 0.05f32..0.45f32,
        // Offset is a fraction in [0, 0.8) of the deadzone count radius,
        // guaranteeing the input is strictly inside the deadzone.
        offset_frac in 0.0f32..0.8f32,
        reversed in proptest::bool::ANY,
    ) {
        let raw_min = 0u32;
        let raw_max = half * 2;
        let raw_center = half;

        // Deadzone radius in raw counts: dz * half (the half-range).
        let dz_counts = (dz * half as f32) as u32;
        let raw_offset = ((offset_frac * dz_counts as f32) as u32).min(dz_counts);
        let raw_inside = raw_center.saturating_add(raw_offset).min(raw_max);

        let cal = AxisCalibration {
            raw_min,
            raw_max,
            raw_center,
            deadzone: dz,
            output_min: -1.0,
            output_max: 1.0,
            reversed,
        };

        let out_center = cal.normalize(raw_center);
        let out_inside = cal.normalize(raw_inside);

        prop_assert!(
            out_inside == out_center,
            "raw {} (inside deadzone={}) → {}, but normalize(raw_center={}) = {}",
            raw_inside, dz, out_inside, raw_center, out_center
        );
    }
}

// ---------------------------------------------------------------------------
// Invariant 7: Reverse flag swaps endpoints
// ---------------------------------------------------------------------------

proptest! {
    /// For a reversed axis (no deadzone), `raw_min → output_max` and
    /// `raw_max → output_min` (exact symmetry with the forward case).
    #[test]
    fn reverse_flag_swaps_endpoints(
        raw_min in 0u32..65534u32,
        raw_spread in 1u32..=65535u32,
        ctr_frac in 0.0f32..=1.0f32,
        (out_min, out_max) in bipolar_output(),
    ) {
        let raw_max = raw_min.saturating_add(raw_spread);
        let raw_center = raw_min + (ctr_frac * (raw_max - raw_min) as f32) as u32;
        let raw_center = raw_center.min(raw_max);

        let forward = AxisCalibration {
            raw_min,
            raw_max,
            raw_center,
            deadzone: 0.0,
            output_min: out_min,
            output_max: out_max,
            reversed: false,
        };
        let reversed = AxisCalibration { reversed: true, ..forward.clone() };

        let fwd_at_min = forward.normalize(raw_min);
        let rev_at_min = reversed.normalize(raw_min);
        let fwd_at_max = forward.normalize(raw_max);
        let rev_at_max = reversed.normalize(raw_max);

        prop_assert!(
            (fwd_at_min - out_min).abs() < 1e-4,
            "forward raw_min → {fwd_at_min}, expected {out_min}"
        );
        prop_assert!(
            (rev_at_min - out_max).abs() < 1e-4,
            "reversed raw_min → {rev_at_min}, expected {out_max}"
        );
        prop_assert!(
            (fwd_at_max - out_max).abs() < 1e-4,
            "forward raw_max → {fwd_at_max}, expected {out_max}"
        );
        prop_assert!(
            (rev_at_max - out_min).abs() < 1e-4,
            "reversed raw_max → {rev_at_max}, expected {out_min}"
        );
    }
}

// ---------------------------------------------------------------------------
// Invariant 8: Resolution tolerance (10-bit, 12-bit, 16-bit, unipolar)
// ---------------------------------------------------------------------------

proptest! {
    /// 10-bit axes (0–1023) always produce finite, bounded output.
    #[test]
    fn resolution_10bit_always_finite_and_bounded(
        raw in 0u32..=1023u32,
        dz in deadzone(),
        reversed in proptest::bool::ANY,
    ) {
        let cal = AxisCalibration {
            raw_min: 0,
            raw_max: 1023,
            raw_center: 511,
            deadzone: dz,
            output_min: -1.0,
            output_max: 1.0,
            reversed,
        };
        let out = cal.normalize(raw);

        prop_assert!(out.is_finite(), "10-bit: raw={raw} → {out} is not finite");
        prop_assert!(
            (-1.0..=1.0).contains(&out),
            "10-bit: raw={raw} → {out} is outside [-1, 1]"
        );
    }

    /// 12-bit axes (0–4095) always produce finite, bounded output.
    #[test]
    fn resolution_12bit_always_finite_and_bounded(
        raw in 0u32..=4095u32,
        dz in deadzone(),
        reversed in proptest::bool::ANY,
    ) {
        let cal = AxisCalibration {
            raw_min: 0,
            raw_max: 4095,
            raw_center: 2047,
            deadzone: dz,
            output_min: -1.0,
            output_max: 1.0,
            reversed,
        };
        let out = cal.normalize(raw);

        prop_assert!(out.is_finite(), "12-bit: raw={raw} → {out} is not finite");
        prop_assert!(
            (-1.0..=1.0).contains(&out),
            "12-bit: raw={raw} → {out} is outside [-1, 1]"
        );
    }

    /// 16-bit axes (0–65535) always produce finite, bounded output.
    #[test]
    fn resolution_16bit_always_finite_and_bounded(
        raw in 0u32..=65535u32,
        dz in deadzone(),
        reversed in proptest::bool::ANY,
    ) {
        let cal = AxisCalibration {
            raw_min: 0,
            raw_max: 65535,
            raw_center: 32767,
            deadzone: dz,
            output_min: -1.0,
            output_max: 1.0,
            reversed,
        };
        let out = cal.normalize(raw);

        prop_assert!(out.is_finite(), "16-bit: raw={raw} → {out} is not finite");
        prop_assert!(
            (-1.0..=1.0).contains(&out),
            "16-bit: raw={raw} → {out} is outside [-1, 1]"
        );
    }

    /// Throttle axes (0–65535, unipolar [0, 1]) always produce finite, bounded output.
    #[test]
    fn throttle_unipolar_always_finite_and_bounded(
        raw in 0u32..=65535u32,
        reversed in proptest::bool::ANY,
    ) {
        let cal = AxisCalibration {
            raw_min: 0,
            raw_max: 65535,
            raw_center: 0,
            deadzone: 0.0,
            output_min: 0.0,
            output_max: 1.0,
            reversed,
        };
        let out = cal.normalize(raw);

        prop_assert!(out.is_finite(), "throttle: raw={raw} → {out} is not finite");
        prop_assert!(
            (0.0..=1.0).contains(&out),
            "throttle: raw={raw} → {out} is outside [0, 1]"
        );
    }
}

// ---------------------------------------------------------------------------
// Regression / unit-style checks
// ---------------------------------------------------------------------------

/// Sanity-check the canonical 16-bit symmetric stick (no deadzone).
#[test]
fn canonical_16bit_stick_spot_checks() {
    let cal = AxisCalibration {
        raw_min: 0,
        raw_max: 65535,
        raw_center: 32767,
        deadzone: 0.0,
        output_min: -1.0,
        output_max: 1.0,
        reversed: false,
    };

    assert!(
        (cal.normalize(0) - (-1.0)).abs() < 1e-4,
        "raw 0 should give -1.0"
    );
    assert!(
        (cal.normalize(32767) - 0.0).abs() < 1e-3,
        "raw_center should give ~0.0"
    );
    assert!(
        (cal.normalize(65535) - 1.0).abs() < 1e-4,
        "raw_max should give 1.0"
    );
}

/// A reversed 8-bit throttle: raw=0 → 1.0, raw=255 → 0.0.
#[test]
fn reversed_8bit_throttle() {
    let cal = AxisCalibration {
        raw_min: 0,
        raw_max: 255,
        raw_center: 0,
        deadzone: 0.0,
        output_min: 0.0,
        output_max: 1.0,
        reversed: true,
    };

    assert!(
        (cal.normalize(0) - 1.0).abs() < 1e-4,
        "raw 0 reversed → 1.0"
    );
    assert!(
        (cal.normalize(255) - 0.0).abs() < 1e-4,
        "raw 255 reversed → 0.0"
    );
}

/// A 10% deadzone should snap small stick inputs near centre to the centre value.
#[test]
fn deadzone_snaps_small_inputs_to_center() {
    let cal = AxisCalibration {
        raw_min: 0,
        raw_max: 65535,
        raw_center: 32767,
        deadzone: 0.10,
        output_min: -1.0,
        output_max: 1.0,
        reversed: false,
    };

    // Compute the actual centre output; may be slightly off 0.0 because
    // 32767 / 65535 ≈ 0.499992 (not exactly 0.5).
    let centre_out = cal.normalize(cal.raw_center);

    // A small nudge (~3% off centre) is well inside the 10% deadzone.
    let small_nudge = 32767u32 + 1000;
    assert_eq!(
        cal.normalize(small_nudge),
        centre_out,
        "small nudge inside 10% deadzone should snap to centre output {centre_out}"
    );

    // Full deflection must not be snapped.
    assert!(
        cal.normalize(65535) > 0.5,
        "full positive deflection must be > 0.5 even with 10% deadzone"
    );
    assert!(
        cal.normalize(0) < -0.5,
        "full negative deflection must be < -0.5 even with 10% deadzone"
    );
}
